IMAGES_DIRECTORY = "./data/training_photos"
USER_UPLOAD_DIR = "./data/queries_photos"
TMP_FILE_TO_STORE_DESCRIPTIONS = "./data/descriptors/description.pkl"
RE_INDEX_INTERVAL_SEC = 10
RE_FETCH_INTERVAL_SEC = 15
COLOR_DESCRIPTOR_TUPLE = (8, 12, 3)
SAVE_WHOLE_VALIDATION_SET = True
TRAINING_LOG_THRESHOLD = 1000
